In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv("C:\\Users\\ad\\Downloads\\Shark Tank India Dataset.csv")
df.head()

,episode_number,pitch_number,brand_name,idea,deal,pitcher_ask_amount,ask_equity,ask_valuation,deal_amount,deal_equity,...,ashneer_deal,anupam_deal,aman_deal,namita_deal,vineeta_deal,peyush_deal,ghazal_deal,total_sharks_invested,amount_per_shark,equity_per_shark
0,1,1,BluePine Industries,Frozen Momos,1,50.0,5.0,1000.00,75.0,16.00,...,1,0,1,0,1,0,0,3,25.0,5.333333
1,1,2,Booz scooters,Renting e-bike for mobility in private spaces,1,40.0,15.0,266.67,40.0,50.00,...,1,0,0,0,1,0,0,2,20.0,25.000000
2,1,3,Heart up my Sleeves,Detachable Sleeves,1,25.0,10.0,250.00,25.0,30.00,...,0,1,0,0,1,0,0,2,12.5,15.000000
3,2,4,Tagz Foods,Healthy Potato Chips,1,70.0,1.0,7000.00,70.0,2.75,...,1,0,0,0,0,0,0,1,70.0,2.750000
4,2,5,Head and Heart,Brain Development Course,0,50.0,5.0,1000.00,0.0,0.00,...,0,0,0,0,0,0,0,0,0.0,0.000000

### checking shape of data

In [3]:
df.shape

(117, 28)

### checking  null values

In [4]:
df.isnull().sum()

episode_number           0
pitch_number             0
brand_name               0
idea                     0
deal                     0
pitcher_ask_amount       0
ask_equity               0
ask_valuation            0
deal_amount              0
deal_equity              0
deal_valuation           0
ashneer_present          0
anupam_present           0
aman_present             0
namita_present           0
vineeta_present          0
peyush_present           0
ghazal_present           0
ashneer_deal             0
anupam_deal              0
aman_deal                0
namita_deal              0
vineeta_deal             0
peyush_deal              0
ghazal_deal              0
total_sharks_invested    0
amount_per_shark         0
equity_per_shark         0
dtype: int64

In [5]:
df.columns

Index(['episode_number', 'pitch_number', 'brand_name', 'idea', 'deal',
       'pitcher_ask_amount', 'ask_equity', 'ask_valuation', 'deal_amount',
       'deal_equity', 'deal_valuation', 'ashneer_present', 'anupam_present',
       'aman_present', 'namita_present', 'vineeta_present', 'peyush_present',
       'ghazal_present', 'ashneer_deal', 'anupam_deal', 'aman_deal',
       'namita_deal', 'vineeta_deal', 'peyush_deal', 'ghazal_deal',
       'total_sharks_invested', 'amount_per_shark', 'equity_per_shark'],
      dtype='object')

In [6]:
df.dtypes

episode_number             int64
pitch_number               int64
brand_name                object
idea                      object
deal                       int64
pitcher_ask_amount       float64
ask_equity               float64
ask_valuation            float64
deal_amount              float64
deal_equity              float64
deal_valuation           float64
ashneer_present            int64
anupam_present             int64
aman_present               int64
namita_present             int64
vineeta_present            int64
peyush_present             int64
ghazal_present             int64
ashneer_deal               int64
anupam_deal                int64
aman_deal                  int64
namita_deal                int64
vineeta_deal               int64
peyush_deal                int64
ghazal_deal                int64
total_sharks_invested      int64
amount_per_shark         float64
equity_per_shark         float64
dtype: object

In [10]:
## total deal of aman 
df["aman_deal"].value_counts()

0    89
1    28
Name: aman_deal, dtype: int64

In [16]:
df['brand_name'].unique()

array(['BluePine Industries', 'Booz scooters', 'Heart up my Sleeves',
       'Tagz Foods', 'Head and Heart', 'Agro tourism', 'Qzense Labs',
       'Peeschute', 'NOCD', 'Cosiq', 'JhaJi Achaar', 'Bummer',
       'Revamp Moto', 'Hungry Heads', 'Shrawani Engineers', 'Skippi Pops',
       'Menstrupedia', 'Hecolll', 'Raising Superstars', 'Torch-it',
       'La Kheer Deli', 'Beyond Snack', 'Vivalyf Innovations- Easy Life',
       'Motion Breeze', 'Altor', 'Ariro', 'Kabira Handmade', 'Nuutjob',
       'Meatyour', 'EventBeep', "Gopal's 56", 'ARRCOAT Surface Textures',
       'Farda', 'Auli Lifestyle', 'SweeDesi', 'LOKA', 'Annie',
       'Caragreen', 'The Yarn Bazaar', 'The Renal Project',
       'Morikko Pure Foods', 'Good Good Piggy Bank', 'Hammer Lifestyle',
       'PNT', 'Cocofit', 'Bamboo India', 'Flying Furr', 'Beyond Water',
       "Let's Try", 'Find Your Kicks India', 'Aas Vidyalaya', 'Outbox',
       'RoadBounce', "Mommy's Kitchen", 'India Hemp and Co', 'Otua',
       'Anthyesti', 'Ethik', 'WeSTOCK', 'KetoIndia', 'Magic lock',
       'The State Plate', 'Bakarmax', 'IN A CAN', 'Get a Whey',
       'Sid07 Designs', 'The Quirky Nari', 'Hair Originals',
       'Poo de Cologne', 'Moonshine Meads', 'Falhari', 'Namhya Foods',
       'Urban Monkey', 'Guardian Gears', 'Modern Myth', 'The Sass Bar',
       'KG Agrotech', 'Nuskha Kitchen', 'PawsIndia',
       'Sunfox Technologies', 'Alpino', 'Isak Fragrances',
       'Julaa Automation', 'Rare Planet', 'Theka Coffee',
       'Watt Technovations', 'Aliste Technologies', 'Insurance Samadhan',
       'Humpy A2', 'Kunafa World', 'Gold Safe Solutions Ind.',
       'Wakao Foods', 'PDD Falcon', 'PlayBox TV',
       'Sippline Drinking Shields', 'Kabaddi Adda', 'Shades of Spring',
       'Scholify', 'Scrapshala', 'Sabjikothi', 'AyuRythm', 'Astrix',
       'Thea and Sid', 'Experential Etc', 'GrowFitter', 'Med Tech',
       'Colour Me Mad', "Mavi's", 'Tweek Labs', 'Proxgy',
       'Nomad Food Project', 'Twee in One', 'Green Protein', 'On2Cook',
       'Jain Shikanji', 'Woloo', 'Elcare India'], dtype=object)

In [19]:
### maxm pichter amount ask
df["pitcher_ask_amount"].agg(["min","max","sum"])

min        0.00101
max    30000.00000
sum    37423.00101
Name: pitcher_ask_amount, dtype: float64

In [8]:
df["episode_number"].nunique()

35

In [12]:
df["deal"].max()

1

In [11]:
### random values of data
df.sample(10)

,episode_number,pitch_number,brand_name,idea,deal,pitcher_ask_amount,ask_equity,ask_valuation,deal_amount,deal_equity,...,ashneer_deal,anupam_deal,aman_deal,namita_deal,vineeta_deal,peyush_deal,ghazal_deal,total_sharks_invested,amount_per_shark,equity_per_shark
32,11,33,Farda,Customised Streetwear,1,30.0,10.0,300.00,30.0,20.0,...,0,0,1,1,0,0,0,2,15.0,10.0
114,35,115,Jain Shikanji,Lemonade,1,40.0,8.0,500.00,40.0,30.0,...,1,1,1,0,1,0,0,4,10.0,7.5
4,2,5,Head and Heart,Brain Development Course,0,50.0,5.0,1000.00,0.0,0.0,...,0,0,0,0,0,0,0,0,0.0,0.0
9,4,10,Cosiq,Intelligent Skincare,1,50.0,7.5,666.67,50.0,25.0,...,0,1,0,0,1,0,0,2,25.0,12.5
73,23,74,Guardian Gears,Motorcycle Luggage,0,30.0,5.0,600.00,0.0,0.0,...,0,0,0,0,0,0,0,0,0.0,0.0
37,13,38,Caragreen,Eco-Friendly boxes,1,50.0,10.0,500.00,50.0,20.0,...,0,1,0,0,0,1,0,2,25.0,10.0
65,21,66,Sid07 Designs,Inventions,1,47.0,10.0,470.00,25.0,75.0,...,0,0,0,0,0,1,0,1,25.0,75.0
81,26,82,Isak Fragrances,Perfumes,1,50.0,8.0,625.00,50.0,50.0,...,0,0,0,0,0,1,0,1,50.0,50.0
92,29,93,PDD Falcon,Stainless Steel Items,0,75.0,3.0,2500.00,0.0,0.0,...,0,0,0,0,0,0,0,0,0.0,0.0
48,16,49,Let's Try,Healthy Snacks,1,45.0,2.0,2250.00,45.0,12.0,...,0,1,1,0,0,0,0,2,22.5,6.0

In [9]:
df["episode_number"].value_counts()  ##frequency of each deal per episode

18    4
30    4
17    4
16    4
22    4
23    4
27    4
31    4
32    4
33    4
34    4
19    4
29    3
28    3
20    3
26    3
25    3
24    3
21    3
1     3
2     3
15    3
14    3
13    3
12    3
11    3
10    3
9     3
8     3
7     3
6     3
5     3
4     3
3     3
35    3
Name: episode_number, dtype: int64

In [ ]:
plt.figure(figsize=(12,8))
sns.countplot(df[""])